### PR TITLE
add base OpKernel and Conv2dKernel skeletons

### PR DESCRIPTION
**Pull request by edgarriba**
Quick PR to introduce OpKernel and Conv2dCustomOp

### CODE REVIEW

**Comment by Wangyida** [comment]
There improper implementation on efficient quantized kernels with additional range representation [conv2d_eq etc.](https://github.com/nyanp/tiny-cnn/blob/feat/generic-computational-graph/tiny_cnn/core/backend_tiny.h). These 3 method could be reconsidered in data flow.

**Comment by edgarriba** [comment]
@nyanp @Wangyida If we all agree with this design, can we go ahead merging to not block other tasks?

**Comment by Wangyida** [comment]
@edgarriba Seems OK for me as I'm on serialise branch now.

**Comment by nyanp** [comment]
@edgarriba 
Sure! It's ok for me ;)

**Pull request merged**
