### PR TITLE
Add Device, Program ans ProgramManager to register Ops

### PR DESCRIPTION
**Pull request by edgarriba**

### CODE REVIEW

**Comment by edgarriba** [comment]
@nyanp I think we could merge this and start with Ops integration into a new PR. 
Let me squash commits and go ahead.

**Comment by nyanp** [comment]
@edgarriba 
Ok I'll merge it. Regarding #249 is still unresolved.. /cc @Wangyida  any update?

**Comment by Wangyida** [comment]
@nyanp Could you have a look on it? I forget to push 1 commit codes are rebased now, seems all warning related to quantization are fixed in regard to Edgar's script of building log.

**Comment by nyanp** [comment]
@Wangyida 
Good, I've posted some comments on your PR.

@edgarriba 
As you noticed from compiler error, we need to conceal clcuda types if we haven't OpenCL/CUDA options.

**Comment by edgarriba** [comment]
@Wangyida fixed that in https://github.com/nyanp/tiny-cnn/pull/264

**Comment by Wangyida** [comment]
@ OK, I'll rebase on it.

**Pull request merged**
