### PR TITLE
Adapt Caffe importer to new generic-computational-graph branch

### PR DESCRIPTION
**Pull request by edgarriba**
This PR pretends to adapt the Caffe importer to the new computational graph API.

*STATUS*
- Compiling and getting segfaults
- Need to check all **TODO**

### CODE REVIEW

**Comment by nyanp** [comment]
@edgarriba Amazing quick work :+1:  What is your task in next few days, solving these TODO, or designing optimization backend?

**Comment by edgarriba** [comment]
First I'll try to fix this TODO. If you have any suggestion, go ahead. After that we can start to design the backend API. I'll comment your nice schedule in the other thread 😉

**Comment by nyanp** [comment]
@edgarriba
Ok, I'll wait for your fix 😀 BTW, what kind of formatting tool / lint tool do you use? I want to use the same settings to you to keep source codes consistent.

**Comment by edgarriba** [comment]
https://github.com/google/styleguide

**Pull request merged**
