### PR TITLE
Implementation on deconvolution and unpooling layer

### PR DESCRIPTION
**Pull request by Wangyida**
This PR is based on feat/generic-computational-graph branch of nyanp/tiny-cnn.
Mostly including deconvolution layer and unpooling layer which is prepared for deconvolution network for semantic segmentation.

### CODE REVIEW

**Comment by edgarriba** [comment]
Hi @Wangyida ! Awesome contrib.

/cc @bhack @mtamburrano
Just say that in few days there will be some changes in the API.
Track this PR: https://github.com/nyanp/tiny-cnn/pull/166

**Comment by Wangyida** [comment]
@edgarriba Nice, I have already found that this branch is much more different from master branch. I am also still debugging these codes for my API.

**Comment by edgarriba** [comment]
yes, there several changes from master. Now it's more oriented to be like a real graph with Node-Edge relations

**Comment by Wangyida** [comment]
@edgarriba That's great to be able to use a real graph with Node-Edge relations.

@bhack @mtamburrano My max_unpooling layer must be implemented in this mode because the input of max_unpooling layer is dependent on 2 input: output from last layer and max_pooling mask from previous max_pooling layer and the max_pooling layer should have 2 outputs which are output and max_index mask.

Now my unpooling layer is implemented in an average_unpooling style which is not dependent on previous pooling mask.

**Comment by nyanp** [comment]
@Wangyida
Great! I've merged this branch into base, so your code will work on both base&branch. Is your debugging completed?

**Comment by edgarriba** [comment]
@nyanp @Wangyida Do you think that we could add in the API conv auto encoders using that?

**Comment by Wangyida** [comment]
@nyanp Hi, Yes, my codes for deconvolutional layer, unpooling layer is tested well, and I also provided a test example in exmples/deconv folder. All codes are debuged and I think you could merge them now and I will start to further modify my max unpooling layer for a graph like network as Edgar described.

@edgarriba I think it is possible to do such thing, and a traditional auto encoder is only dependent on conv layer, pooling layer and fully connected layer, some layer work is based on some deconvolutional concept.

**Comment by nyanp** [comment]
@Wangyida 
> my codes for deconvolutional layer, unpooling layer is tested well, and I also provided a test example in exmples/deconv folder

Perfect :+1: I'll merge it both branch and base. Thank you very much!

**Comment by Wangyida** [comment]
@nyanp Alright, thanks! I might change some inefficient details about these codes according to the updating graph-like contributed by Edgar, it will be another PR together with the max_unpooling codes using the max_index produced by max_pooling layer. And a automatic quantization methods on parametric model might also be provided layer.

**Comment by nyanp** [comment]
@Wangyida 
I'm really looking forward to it! And I'd very happy if you add a simple description document as examples/deconv/readme.md :)

**Pull request merged**
