### PR TITLE
Fixes to previous PR #81

### PR DESCRIPTION
**Pull request by pansk**
My previous PR broke pre-VS2013 compatibility (VS2013 doesn't allow defaulted move constructor).
Added a small utility for this in util.h (defining CNN_DEFAULT_MOVE_CONSTRUCTOR_UNAVAILABLE and CNN_DEFAULT_ASSIGNMENT_OPERATOR_UNAVAILABLE in this case).

### CODE REVIEW

**Comment by patrikhuber** [comment]
What about just dropping support for VS2012? It's getting pretty old. Most people should be on VS2015, or at least 2013. Would make the code simpler and more readable.

**Comment by pansk** [comment]
+1

I just noticed that my comment is a bit ambiguous.
Defaulting move constructor/assignment is unavailable in VS2013 too (only VS2015 supports that C++11 feature).

**Comment by stereomatchingkiss** [comment]
Please do not give up the support of vs2013, because cuda do not support vs2015 yet, it would be quite tedious to maintain two versions of lib/dll on windows platform.

**Comment by pansk** [comment]
Same problem here, that's the main reason of this PR. Unfortunately it will drop the move semantics on these objects from VS2013 (but at the moment having move semantics for these objects is not important in this version of tiny-cnn).

**Comment by nyanp** [comment]
+1
I want to keep support for vs2013 (portability is important for tiny-cnn) , but I think stop supporting vs2012 is acceptable. Thanks for nice PRs :)

**Pull request merged**
