### PR TITLE
Modified paths in includes, CMake

### PR DESCRIPTION
**Pull request by mrazekv**
Updated paths for include
Modified CMake to reflect these changes
Add OpenCV package requirement to CMakeList

The current version is not working on Linux with gcc+cmake, so I have modified the code

### CODE REVIEW

**Comment by patrikhuber** [comment]
The changes to the paths to the headerfiles in CMakeLists.txt might indeed be necessary, but using "../" in include-paths can lead to problems and I think I would consider it bad practice.
[Related SO question](http://stackoverflow.com/questions/597318/what-are-the-benefits-of-a-relative-path-such-as-include-header-h-for-a-hea?lq=1). 

Having the includes as `#include "tiny_cnn/layers/fully_connected_layer.h"` is standard and it works, given the rest of the setup is working properly.

**Comment by nyanp** [comment]
@mrazekv 
Thanks a lot for nice PR, and I agree with @patrikhuber . Could you rebase header files?

**Comment by mrazekv** [comment]
@patrikhuber I agree, I have forgotten to set the direct paths. I'm not sure why the gcc had a problem with it. I will revert these files back in next week and then I will re-push these changes. Thank you for your work!

**Comment by mrazekv** [comment]
@nyanp Hi, I have changed CMakeFile definition and opencv include in the pull request. I allso add include definition to prevent using "../" in includes. Everything works fine for me. I hope there will be no problem with pulling.

**Pull request merged**
